tabquiz/urls.py
from django.urls import path

from . import views
from tabquiz.views import LessonIndexView


app_name='tabquiz'
urlpatterns = [
    path('', LessonIndexView.as_view(), name='index'),
    path('lesson/<int:lesson_id>/', views.lesson, name='lesson'),
]

tabtester/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import settings


urlpatterns = [
    path('', include('tabquiz.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^nested_admin/', include('nested_admin.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

tabquiz/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Lesson(models.Model):
    lesson_id = models.IntegerField(
        primary_key=True,
        verbose_name=_('lesson id'),
    )

    description = models.CharField(max_length=200)

    def __str__(self):
        return self.description

    class Meta:
        verbose_name = _('Lesson')
        verbose_name_plural = _('Lessons')


class Question(models.Model):
    level = models.ForeignKey('Lesson', on_delete=models.CASCADE,)

    question_id = models.AutoField(primary_key=True)

    text = models.CharField(
        max_length=200,
        verbose_name=_('text'),
    )

    image = models.ImageField(
        upload_to='image/',
        default=None,
        blank=True)

    is_final = models.BooleanField(
        default=False,
        # Translators: indicates the final question of a lesson
        verbose_name=_('final question')
    )

    def __str__(self):
        return self.text


class Choice(models.Model):
    level = models.ForeignKey('Question', on_delete=models.CASCADE,)

    next_question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        related_name='parent_choice',
        default='',
        null=True,
        blank=True,
        verbose_name=_("next question"),
    )

    choice_text = models.CharField(
        max_length=200,
        verbose_name=_('choice text'),
    )

    def __str__(self):
        return self.choice_text

    class Meta:
        verbose_name = _('Choices')
        verbose_name_plural = _('Choices')

tabquiz/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.list import ListView

from .models import Lesson, Question, Choice


class LessonIndexView(ListView):
    model = Lesson
    template_name = 'tabquiz/index.html'
    context_object_name = 'lesson_list'


def lesson(request, lesson_id):
    lesson = get_object_or_404(Lesson, lesson_id=lesson_id)
    if request.method == 'GET':
        # FIXME: should not be hardcoded to question[0]
        question = lesson.question_set.all()[0]
        route = list()

    elif request.method == 'POST':
        choice = Choice.objects.get(pk=request.POST['choice'])
        question = choice.next_question
        route = request.session['route']
        route.append(question.pk)

    request.session['route'] = route
    trace_route = [Question.objects.get(pk=pk) for pk in route]
    print(trace_route)
    context = {
        'lesson': lesson,
        'lesson_list': Lesson.objects.all(),
        'question': question,
        'choices': question.choice_set.all(),
        'route': route,
        'trace_route': trace_route
    }
    return render(request, 'tabquiz/lesson.html', context)

tabquiz/templates/tabquiz/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>

    <!-- Mobile first -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Translation tags -->
    {% load i18n %}

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <!-- Custom css -->
    {% load static %}
    <link rel="stylesheet" type="text/css"
          href="{% static 'tabquiz/style.css' %}">
    <title>TabQuiz</title>

  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'tabquiz:index' %}">TabQuiz</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'tabquiz:index' %}">
              {% trans 'Lessons index' %}
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {% trans 'Lessons' %}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for lesson in lesson_list %}
                <a class="dropdown-item" href={% url 'tabquiz:lesson' lesson.lesson_id %}>
                  {{lesson.lesson_id}} - {{lesson.description}}
                </a>
              {% endfor %}
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">
              {% trans 'Administration' %}
            </a>
          </li>
        </ul>
      </div>
    </nav>
  {% block content %}
  {% endblock %}
  </body>
</html>

tabquiz/templates/tabquiz/index.html
{% extends 'tabquiz/base.html' %}
{% block content %}
<main class="text-center">
  <h2>Menu des leçons</h2>
  <ul class="list-group">
    {% for lesson in lesson_list %}
      <li><a href={% url 'tabquiz:lesson' lesson.lesson_id %}>
        {{lesson.lesson_id}} -- {{lesson.description}}
      </a></li>
    {% endfor %}
  </ul>
</main>
{% endblock %}

tabquiz/templates/tabquiz/lesson.html
{% extends 'tabquiz/base.html' %}
{% load static %}
{% load i18n %}

{% block content %}

<div class="container text-center">
  <header>
    <h2>{% trans "Lesson" %} {{lesson.lesson_id}}</h2>
  </header>

  {% if error_message %}
    <p><strong>{{ error_message }}</strong> </p>
  {% endif %}

  {% if question.image != "" %}
    <img src="{{question.image.url}}" alt="Your image here">
  {% endif %}
  <p> {{ question.text }} </p>
  <form action="{% url 'tabquiz:lesson' lesson.lesson_id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <div class="form-group">
      <input type="radio" name="choice" id="choice{{ forloop.counter }}"
             class="form-radio-input"
             value="{{ choice.id }}"
             required/>
      <label for="choice{{ forloop.counter }}"
             class="radio-inline control-label">
        {{ choice.choice_text }}
      </label>
      <br>
    </div>
    {% endfor %}
    <br>

    <!-- prevent submit if no choices -->
    {% if choices.all %}
      <input type="submit" value="Choisir">
    {% endif %}
  </form>
  {% if question.is_final %}
    <p>{% trans "your path" %} :</p>
    <style>
      .list-group-item {
        display: list-item
      }
    </style>
    <ol class="list-group">
    {% for q in trace_route %}
      <li class="list-group-item">{{ q.text }}</li>
    {% endfor %}
  {% endif %}
</div>


{% endblock %}